// Blacklist is for words that are capitalized or have the same feature shape as a place
//	and show up a lot on web pages
// 	but almost never used to identify a location
// In the parser, these words are often considered to be places
//	but they shouldn't be mapped
function blacklistLexicon() {
	lexicon = {
		"Mercury":"Planet",
		"Venus":"Planet",
		"Earth":"Planet",
		"Mars":"Planet",
		"Jupiter":"Planet",
		"Saturn":"Planet",
		"Uranus":"Planet",
		"Neptune":"Planet",
		"Pluto":"Planet",
		"There":"Misc",
		"Terms":"Misc",
		"Service":"Misc",
		"Sale":"Misc",
		"Copyright":"Misc",
		"Trademark":"Misc",
		"There":"Misc",
		"President":"Misc",
		"Prime Minister":"Misc",
		"Democrat":"Misc",
		"Republican":"Misc",
		"House":"Misc",
		"Senate":"Misc",
		"Senator":"Misc",
		"Representative":"Misc",
		"Secretary":"Misc",
		"Congress":"Misc",
		"Monday":"Date",
		"Tuesday":"Date",
		"Wednesday":"Date",
		"Thursday":"Date",
		"Friday":"Date",
		"Saturday":"Date",
		"Sunday":"Date",
		"January":"Date",
		"February":"Date",
		"March":"Date",
		"April":"Date",
		"May":"Date",
		"June":"Date",
		"July":"Date",
		"August":"Date",
		"September":"Date",
		"October":"Date",
		"November":"Date",
		"December":"Date",
		"Jan":"Date",
		"Feb":"Date",
		"Mar":"Date",
		"Apr":"Date",
		"Jun":"Date",
		"Jul":"Date",
		"Aug":"Date",
		"Sept":"Date",
		"Oct":"Date",
		"Nov":"Date",
		"Dec":"Date",
		"Walmart":"Organization",
		"Exxon Mobil":"Organization",
		"Apple":"Organization",
		"Berkshire Hathaway":"Organization",
		"McKesson":"Organization",
		"UnitedHealth Group":"Organization",
		"CVS Health":"Organization",
		"CVS":"Organization",
		"CVS Pharmacy":"Organization",
		"General Motors":"Organization",
		"Ford Motor":"Organization",
		"AT&T":"Organization",
		"General Electric":"Organization",
		"GE":"Organization",
		"AmerisourceBergen":"Organization",
		"Verizon":"Organization",
		"Chevron":"Organization",
		"Costco":"Organization",
		"Fannie Mae":"Organization",
		"Kroger":"Organization",
		"Amazon":"Organization",
		"Walgreens Boots Alliance":"Organization",
		"HP":"Organization",
		"Hewlett Packard":"Organization",
		"Cardinal Health":"Organization",
		"Express Scripts Holding":"Organization",
		"J.P. Morgan Chase":"Organization",
		"JP Morgan Chase":"Organization",
		"JP Morgan":"Organization",
		"Boeing":"Organization",
		"Microsoft":"Organization",
		"Bank of America":"Organization",
		"Wells Fargo":"Organization",
		"Home Depot":"Organization",
		"Citigroup":"Organization",
		"Phillips 66":"Organization",
		"Phillips":"Organization",
		"IBM":"Organization",
		"Valero Energy":"Organization",
		"Anthem":"Organization",
		"Procter and Gamble":"Organization",
		"State Farm Insurance":"Organization",
		"State Farm":"Organization",
		"Alphabet":"Organization",
		"Google":"Organization",
		"Comcast":"Organization",
		"Target":"Organization",
    		"Johnson and Johnson":"Organization",
		"MetLife":"Organization",
		"Archer Daniels Midland":"Organization",
		"Marathon Petroleum":"Organization",
		"Freddie Mac":"Organization",
		"PepsiCo":"Organization",
		"United Technologies":"Organization",
		"Aetna":"Organization",
		"Lowe's":"Organization",
		"UPS":"Organization",
		"AIG":"Organization",
		"Prudential Financial":"Organization",
		"Intel":"Organization",
		"Humana":"Organization",
		"Disney":"Organization",
		"Cisco Systems":"Organization",
		"Pfizer":"Organization",
		"Dow Chemical":"Organization",
		"Sysco":"Organization",
		"FedEx":"Organization",
		"Caterpillar":"Organization",
		"Lockheed Martin":"Organization",
		"New York Life Insurance":"Organization",
		"Coca-Cola":"Organization",
		"HCA Holdings":"Organization",
		"Ingram Micro":"Organization",
		"Energy Transfer Equity":"Organization",
		"Tyson Foods":"Organization",
		"American Airlines Group":"Organization",
		"Delta Air Lines":"Organization",
		"Nationwide":"Organization",
		"Johnson Controls":"Organization",
		"Best Buy":"Organization",
		"Merck":"Organization",
		"Liberty Mutual Insurance Group":"Organization",
		"Goldman Sachs Group":"Organization",
		"Honeywell International":"Organization",
		"Massachusetts Mutual Life Insurance":"Organization",
		"Oracle":"Organization",
		"Morgan Stanley":"Organization",
		"Cigna":"Organization",
		"United Continental Holdings":"Organization",
		"Allstate":"Organization",
		"TIAA":"Organization",
		"INTL FCStone":"Organization",
		"CHS":"Organization",
		"American Express":"Organization",
		"Gilead Sciences":"Organization",
		"Publix Super Markets":"Organization",
		"General Dynamics":"Organization",
		"TJX":"Organization",
		"ConocoPhillips":"Organization",
		"Nike":"Organization",
		"World Fuel Services":"Organization",
		"3M":"Organization",
		"Mondelez International":"Organization",
		"Exelon":"Organization",
		"Twenty-First Century Fox":"Organization",
		"Deere":"Organization",
		"Tesoro":"Organization",
		"Time Warner":"Organization",
		"Northwestern Mutual":"Organization",
		"DuPont":"Organization",
		"Avnet":"Organization",
		"Macy's":"Organization",
		"Enterprise Products Partners":"Organization",
		"Travelers Cos.":"Organization",
		"Philip Morris International":"Organization",
		"Rite Aid":"Organization",
		"Tech Data":"Organization",
		"McDonald's":"Organization",
		"Qualcomm":"Organization",
		"Sears Holdings":"Organization",
		"Capital One Financial":"Organization",
		"EMC":"Organization",
		"USAA":"Organization",
		"Duke Energy":"Organization",
		"Time Warner Cable":"Organization",
		"Halliburton":"Organization",
		"Northrop Grumman":"Organization",
		"Arrow Electronics":"Organization",
		"Raytheon":"Organization",
		"Plains GP Holdings":"Organization",
		"US Foods Holding":"Organization",
		"AbbVie":"Organization",
		"Centene":"Organization",
		"Community Health Systems":"Organization",
		"Alcoa":"Organization",
		"International Paper":"Organization",
		"Emerson Electric":"Organization",
		"Union Pacific":"Organization",
		"Amgen":"Organization",
		"U.S. Bancorp":"Organization",
		"Staples":"Organization",
		"Danaher":"Organization",
		"Whirlpool":"Organization",
		"Aflac":"Organization",
		"AutoNation":"Organization",
		"Progressive":"Organization",
		"Abbott Laboratories":"Organization",
		"Dollar General":"Organization",
		"Tenet Healthcare":"Organization",
		"Eli Lilly":"Organization",
		"Southwest Airlines":"Organization",
		"Penske Automotive Group":"Organization",
		"ManpowerGroup":"Organization",
		"Kohl's":"Organization",
		"Starbucks":"Organization",
		"Paccar":"Organization",
		"Cummins":"Organization",
		"Altria Group":"Organization",
		"Xerox":"Organization",
		"Kimberly-Clark":"Organization",
		"Hartford Financial Services Group":"Organization",
		"Kraft Heinz":"Organization",
		"Lear":"Organization",
		"Fluor":"Organization",
		"AECOM":"Organization",
		"Facebook":"Organization",
		"Jabil Circuit":"Organization",
		"CenturyLink":"Organization",
		"Supervalu":"Organization",
		"General Mills":"Organization",
		"Southern":"Organization",
		"NextEra Energy":"Organization",
		"Thermo Fisher Scientific":"Organization",
		"American Electric Power":"Organization",
		"PG&E Corp.":"Organization",
		"NGL Energy Partners":"Organization",
		"Bristol-Myers Squibb":"Organization",
		"Goodyear Tire & Rubber":"Organization",
		"Nucor":"Organization",
		"PNC Financial Services Group":"Organization",
		"Health Net":"Organization",
		"Micron Technology":"Organization",
		"Colgate-Palmolive":"Organization",
		"Freeport-McMoRan":"Organization",
		"ConAgra Foods":"Organization",
		"Gap":"Organization",
		"Baker Hughes":"Organization",
		"Bank of New York Mellon Corp.":"Organization",
		"Dollar Tree":"Organization",
		"Whole Foods Market":"Organization",
		"PPG Industries":"Organization",
		"Genuine Parts":"Organization",
		"Icahn Enterprises":"Organization",
		"Performance Food Group":"Organization",
		"Omnicom Group":"Organization",
		"DISH Network":"Organization",
		"FirstEnergy":"Organization",
		"Monsanto":"Organization",
		"AES":"Organization",
		"CarMax":"Organization",
		"National Oilwell Varco":"Organization",
		"NRG Energy":"Organization",
		"Western Digital":"Organization",
		"Marriott International":"Organization",
		"Office Depot":"Organization",
		"Nordstrom":"Organization",
		"Kinder Morgan":"Organization",
		"Aramark":"Organization",
		"DaVita HealthCare Partners":"Organization",
		"Molina Healthcare":"Organization",
		"WellCare Health Plans":"Organization",
		"CBS":"Organization",
		"Visa":"Organization",
		"Lincoln National":"Organization",
		"Ecolab":"Organization",
		"Kellogg":"Organization",
		"C.H. Robinson Worldwide":"Organization",
		"Textron":"Organization",
		"Loews":"Organization",
		"Illinois Tool Works":"Organization",
		"Synnex":"Organization",
		"Viacom":"Organization",
		"HollyFrontier":"Organization",
		"Land O'Lakes":"Organization",
		"Devon Energy":"Organization",
		"PBF Energy":"Organization",
		"Yum Brands":"Organization",
		"Texas Instruments":"Organization",
		"CDW":"Organization",
		"Waste Management":"Organization",
		"Marsh & McLennan":"Organization",
		"Chesapeake Energy":"Organization",
		"Parker-Hannifin":"Organization",
		"Occidental Petroleum":"Organization",
		"Guardian Life Ins. Co. of America":"Organization",
		"Farmers Insurance Exchange":"Organization",
		"J.C. Penney":"Organization",
		"Consolidated Edison":"Organization",
		"Cognizant Technology Solutions":"Organization",
		"VF":"Organization",
		"Ameriprise Financial":"Organization",
		"Computer Sciences":"Organization",
		"L Brands":"Organization",
		"Jacobs Engineering Group":"Organization",
		"Principal Financial":"Organization",
		"Ross Stores":"Organization",
		"Bed Bath & Beyond":"Organization",
		"CSX":"Organization",
		"Toys \"R\" Us":"Organization",
		"Las Vegas Sands":"Organization",
		"Leucadia National":"Organization",
		"Dominion Resources":"Organization",
		"United States Steel":"Organization",
		"L-Communications":"Organization",
		"Edison International":"Organization",
		"Entergy":"Organization",
		"ADP":"Organization",
		"First Data":"Organization",
		"BlackRock":"Organization",
		"WestRock":"Organization",
		"Voya Financial":"Organization",
		"Sherwin-Williams":"Organization",
		"Hilton Worldwide Holdings":"Organization",
		"R.R. Donnelley & Sons":"Organization",
		"Stanley Black & Decker":"Organization",
		"Xcel Energy":"Organization",
		"Murphy USA":"Organization",
		"CBRE Group":"Organization",
		"D.R. Horton":"Organization",
		"Estee Lauder":"Organization",
		"Praxair":"Organization",
		"Biogen":"Organization",
		"State Street Corp.":"Organization",
		"Unum Group":"Organization",
		"Reynolds American":"Organization",
		"Group Automotive":"Organization",
		"Henry Schein":"Organization",
		"Hertz Global Holdings":"Organization",
		"Norfolk Southern":"Organization",
		"Reinsurance Group of America":"Organization",
		"Public Service Enterprise Group":"Organization",
		"BB&T Corp.":"Organization",
		"DTE Energy":"Organization",
		"Assurant":"Organization",
		"Global Partners":"Organization",
		"Huntsman":"Organization",
		"Becton Dickinson":"Organization",
		"Sempra Energy":"Organization",
		"AutoZone":"Organization",
		"Navistar International":"Organization",
		"Precision Castparts":"Organization",
		"Discover Financial Services":"Organization",
		"Liberty Interactive":"Organization",
		"W.W. Grainger":"Organization",
		"Baxter International":"Organization",
		"Stryker":"Organization",
		"Air Products & Chemicals":"Organization",
		"Western Refining":"Organization",
		"Universal Health Services":"Organization",
		"Owens & Minor":"Organization",
		"Charter Communications":"Organization",
		"Advance Auto Parts":"Organization",
		"MasterCard":"Organization",
		"Applied Materials":"Organization",
		"Eastman Chemical":"Organization",
		"Sonic Automotive":"Organization",
		"Ally Financial":"Organization",
		"CST Brands":"Organization",
		"eBay":"Organization",
		"Lennar":"Organization",
		"GameStop":"Organization",
		"Reliance Steel & Aluminum":"Organization",
		"Hormel Foods":"Organization",
		"Celgene":"Organization",
		"Genworth Financial":"Organization",
		"PayPal Holdings":"Organization",
		"Priceline Group":"Organization",
		"MGM Resorts International":"Organization",
		"Autoliv":"Organization",
		"Fidelity National Financial":"Organization",
		"Republic Services":"Organization",
		"Corning":"Organization",
		"Peter Kiewit Sons'":"Organization",
		"Univar":"Organization",
		"Mosaic":"Organization",
		"Core-Mark Holding":"Organization",
		"Thrivent Financial for Lutherans":"Organization",
		"Cameron International":"Organization",
		"HD Supply Holdings":"Organization",
		"Crown Holdings":"Organization",
		"EOG Resources":"Organization",
		"Veritiv":"Organization",
		"Anadarko Petroleum":"Organization",
		"Laboratory Corp. of America":"Organization",
		"Pacific Life":"Organization",
		"News Corp.":"Organization",
		"Jarden":"Organization",
		"SunTrust Banks":"Organization",
		"Avis Budget Group":"Organization",
		"Broadcom":"Organization",
		"American Family Insurance Group":"Organization",
		"Level Communications":"Organization",
		"Tenneco":"Organization",
		"United Natural Foods":"Organization",
		"Dean Foods":"Organization",
		"Campbell Soup":"Organization",
		"Mohawk Industries":"Organization",
		"BorgWarner":"Organization",
		"PVH":"Organization",
		"Ball":"Organization",
		"O'Reilly Automotive":"Organization",
		"Eversource Energy":"Organization",
		"Franklin Resources":"Organization",
		"Masco":"Organization",
		"Lithia Motors":"Organization",
		"KKR":"Organization",
		"Oneok":"Organization",
		"Newmont Mining":"Organization",
		"PPL":"Organization",
		"SpartanNash":"Organization",
		"Quanta Services":"Organization",
		"XPO Logistics":"Organization",
		"Ralph Lauren":"Organization",
		"Interpublic Group":"Organization",
		"Steel Dynamics":"Organization",
		"WESCO International":"Organization",
		"Quest Diagnostics":"Organization",
		"Boston Scientific":"Organization",
		"AGCO":"Organization",
		"Foot Locker":"Organization",
		"Hershey":"Organization",
		"CenterPoint Energy":"Organization",
		"Williams":"Organization",
		"Dick's Sporting Goods":"Organization",
		"Live Nation Entertainment":"Organization",
		"Mutual of Omaha Insurance":"Organization",
		"W.R. Berkley":"Organization",
		"LKQ":"Organization",
		"Avon Products":"Organization",
		"Darden Restaurants":"Organization",
		"Kindred Healthcare":"Organization",
		"Weyerhaeuser":"Organization",
		"Casey's General Stores":"Organization",
		"Sealed Air":"Organization",
		"Fifth Third Bancorp":"Organization",
		"Dover":"Organization",
		"Huntington Ingalls Industries":"Organization",
		"Netflix":"Organization",
		"Dillard's":"Organization",
		"EMCOR Group":"Organization",
		"Jones Financial":"Organization",
		"AK Steel Holding":"Organization",
		"UGI":"Organization",
		"Expedia":"Organization",
		"salesforce.com":"Organization",
		"Targa Resources":"Organization",
		"Apache":"Organization",
		"Spirit AeroSystems Holdings":"Organization",
		"Expeditors International of Washington":"Organization",
		"Anixter International":"Organization",
		"Fidelity National Information Services":"Organization",
		"Asbury Automotive Group":"Organization",
		"Hess":"Organization",
		"Ryder System":"Organization",
		"Terex":"Organization",
		"Coca-Cola European Partners":"Organization",
		"Auto-Owners Insurance":"Organization",
		"Cablevision Systems":"Organization",
		"Symantec":"Organization",
		"Charles Schwab":"Organization",
		"Calpine":"Organization",
		"CMS Energy":"Organization",
		"Alliance Data Systems":"Organization",
		"JetBlue Airways":"Organization",
		"Discovery Communications":"Organization",
		"Trinity Industries":"Organization",
		"Sanmina":"Organization",
		"NCR":"Organization",
		"FMC Technologies":"Organization",
		"Erie Insurance Group":"Organization",
		"Rockwell Automation":"Organization",
		"Dr Pepper Snapple Group":"Organization",
		"iHeartMedia":"Organization",
		"Tractor Supply":"Organization",
		"J.B. Hunt Transport Services":"Organization",
		"Commercial Metals":"Organization",
		"Owens-Illinois":"Organization",
		"Harman International Industries":"Organization",
		"Baxalta":"Organization",
		"American Financial Group":"Organization",
		"NetApp":"Organization",
		"Graybar Electric":"Organization",
		"Oshkosh":"Organization",
		"Ameren":"Organization",
		"A-Mark Precious Metals":"Organization",
		"Barnes & Noble":"Organization",
		"Dana Holding":"Organization",
		"Constellation Brands":"Organization",
		"LifePoint Health":"Organization",
		"Zimmer Biomet Holdings":"Organization",
		"Harley-Davidson":"Organization",
		"PulteGroup":"Organization",
		"Newell Brands":"Organization",
		"Avery Dennison":"Organization",
		"Jones Lang LaSalle":"Organization",
		"WEC Energy Group":"Organization",
		"Marathon Oil":"Organization",
		"TravelCenters of America":"Organization",
		"United Rentals":"Organization",
		"HRG Group":"Organization",
		"Old Republic International":"Organization",
		"Windstream Holdings":"Organization",
		"Starwood Hotels & Resorts":"Organization",
		"Delek US Holdings":"Organization",
		"Packaging Corp. of America":"Organization",
		"Quintiles Transnational Holdings":"Organization",
		"Hanesbrands":"Organization",
		"Realogy Holdings":"Organization",
		"Mattel":"Organization",
		"Motorola Solutions":"Organization",
		"J.M. Smucker":"Organization",
		"Regions Financial":"Organization",
		"Celanese":"Organization",
		"Clorox":"Organization",
		"Ingredion":"Organization",
		"Genesis Healthcare":"Organization",
		"Peabody Energy":"Organization",
		"Alaska Air Group":"Organization",
		"Seaboard":"Organization",
		"Frontier Communications":"Organization",
		"Amphenol":"Organization",
		"Lansing Trade Group":"Organization",
		"SanDisk":"Organization",
		"St. Jude Medical":"Organization",
		"Wyndham Worldwide":"Organization",
		"Kelly Services":"Organization",
		"Western Union":"Organization",
		"Envision Healthcare Holdings":"Organization",
		"Visteon":"Organization",
		"Arthur J. Gallagher":"Organization",
		"Host Hotels & Resorts":"Organization",
		"Ashland":"Organization",
		"Insight Enterprises":"Organization",
		"Energy Future Holdings":"Organization",
		"Markel":"Organization",
		"Essendant":"Organization",
		"CH2M Hill":"Organization",
		"Western & Southern Financial Group":"Organization",
		"Owens Corning":"Organization",
		"S&P Global":"Organization",
		"Raymond James Financial":"Organization",
		"NiSource":"Organization",
		"Airgas":"Organization",
		"ABM Industries":"Organization",
		"Citizens Financial Group":"Organization",
		"Booz Allen Hamilton Holding":"Organization",
		"Simon Property Group":"Organization",
		"Domtar":"Organization",
		"Rockwell Collins":"Organization",
		"Lam Research":"Organization",
		"Fiserv":"Organization",
		"Spectra Energy":"Organization",
		"Navient":"Organization",
		"Big Lots":"Organization",
		"Telephone & Data Systems":"Organization",
		"First American Financial":"Organization",
		"NVR":"Organization",
		"Cincinnati Financial":"Organization",
		"Burlington Stores":"Organization",
		"Starbucks":"Organization",
		"Google":"Organization",
		"Bbc":"Organization",
		"BBC":"Organization",
		"Apple":"Organization",
		"Aig":"Organization",
		"AIG":"Organization",
		"Amazon":"Organization",
		"Microsoft":"Organization",
		"Guardian":"Organization",
		"Dell Emc":"Organization",
		"Dell":"Organization",
		"Coke":"Organization",
		"Coca-Cola":"Organization",
		"Ford":"Organization",
		"Playstation":"Organization",
		"Ebay":"Organization",
		"Sony":"Organization",
		"Disney":"Organization",
		"Yahoo!":"Organization",
		"Yahoo":"Organization",
		"Sky News":"Organization",
		"Ikea":"Organization",
		"Ibm":"Organization",
		"Nokia":"Organization",
		"Ford Scott Monty":"Organization",
		"Guinness":"Organization",
		"Hp":"Organization",
		"Comcast":"Organization",
		"Skittles":"Organization",
		"Canon":"Organization",
		"Mcdonalds":"Organization",
		"Channel":"Organization",
		"Lego":"Organization",
		"Pepsi":"Organization",
		"Berkshire Hathaway":"Organization",
		"Intel":"Organization",
		"Tesco":"Organization",
		"Nike":"Organization",
		"Honda":"Organization",
		"Bmw":"Organization",
		"T-Mobile":"Organization",
		"Syncforce Client":"Organization",
		"Bt":"Organization",
		"Fedex":"Organization",
		"Vodafone":"Organization",
		"Bosch":"Organization",
		"Ryan Air":"Organization",
		"Ryan Air":"Organization",
		"Toyota":"Organization",
		"Vw":"Organization",
		"Volkswagen":"Organization",
		"Mercedes-Benz":"Organization",
		"Syncforce Client":"Organization",
		"Subway":"Organization",
		"Subway":"Organization",
		"Cadbury":"Organization",
		"Audi":"Organization",
		"Syncforce Client":"Organization",
		"Burger King":"Organization",
		"Marmite":"Organization",
		"Chanel":"Organization",
		"Citibank":"Organization",
		"Easyjet":"Organization",
		"H&M":"Organization",
		"Porsche":"Organization",
		"Zara":"Organization",
		"Gucci":"Organization",
		"Nissan":"Organization",
		"Ups":"Organization",
		"Motorola":"Organization",
		"Avon":"Organization",
		"Marks & Spencer":"Organization",
		"Heinz":"Organization",
		"Rbs":"Organization",
		"Syncforce Client":"Organization",
		"Asda":"Organization",
		"Accenture":"Organization",
		"Hsbc":"Organization",
		"Lexus":"Organization",
		"British Airways":"Organization",
		"Siemens":"Organization",
		"Gillette":"Organization",
		"Barclays":"Organization",
		"Sainsbury":"Organization",
		"Budweiser":"Organization",
		"Louis Vuitton":"Organization",
		"Lovefilm":"Organization",
		"Smirnoff":"Organization",
		"Santander":"Organization",
		"Ubs":"Organization",
		"Shell":"Organization",
		"Colgate-Palmolive Company":"Organization",
		"Citroen":"Organization",
		"Rolex":"Organization",
		"Cartier":"Organization",
		"Knorr":"Organization",
		"Pg Tips":"Organization",
		"Oxo":"Organization",
		"Birds Eye":"Organization",
		"Levis":"Organization",
		"Specsavers":"Organization",
		"Duracell":"Organization",
		"Bp":"Organization",
		"Schweppes":"Organization",
		"Habitat":"Organization",
		"Direct Line":"Organization",
		"Andrex":"Organization",
		"Vauxhall":"Organization",
		"Esri":"Organization"
	}
	return lexicon
}
